class DeanOfficeException(Exception): pass
class StudentNotFoundException(DeanOfficeException): pass
class GroupNotFoundException(DeanOfficeException): pass
class AcademicDebtException(DeanOfficeException): pass
class ExpulsionDeniedException(DeanOfficeException): pass
class InvalidGradeException(DeanOfficeException): pass
class CourseLimitExceededException(DeanOfficeException): pass
class TeacherNotAvailableException(DeanOfficeException): pass
class InvalidTransferException(DeanOfficeException): pass
class ScholarshipDeniedException(DeanOfficeException): pass
class DuplicateEnrollmentException(DeanOfficeException): pass
class ExamNotPassedException(DeanOfficeException): pass
class UnauthorizedAccessException(DeanOfficeException): pass